apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: simple-service
    componentType: service
spec:
    id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:component/4d010f50-96c4-48c0-bab5-a3dd5112b464/5d104332-6726-418a-873a-8d6cafa0b858
    name: simple-service
    slug: svc-simple-service
    description: Simple-service is a no-nonsense, do-what-it-needs-to-do kind of service. It reads a lot, writes a little, and somehow still manages to act important. If databases had best friends, Simple RDS would be its ride-or-die.
    configVersion: 0
    typeId: SERVICE
    ownerId: ari:cloud:identity::team/f4797497-61c0-4312-93f3-8d0f31ace225
    dependsOn:
        - kubernetes
        - kubernetes
    fields:
        lifecycle: Active
        tier: 4
    links: []
    documents: []
    labels:
        - simple-service
        - cloud-runtime
        - platform
    metricSources: {}
    tribe: platform
    squad: cloud-runtime
