apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: streaming-service
    componentType: service
spec:
    id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:component/4d010f50-96c4-48c0-bab5-a3dd5112b464/f01a9d11-c180-4703-8b03-3755838709ec
    name: streaming-service
    slug: ""
    description: ""
    configVersion: 0
    typeId: SERVICE
    ownerId: ""
    dependsOn: []
    links:
        - id: ""
          name: Repository
          type: REPOSITORY
          url: https://github.com/motain/streaming-service
        - id: ""
          name: Monitoring page
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=streaming-service&var-container=streaming-service&from=now-1h&to=now
        - id: ""
          name: OnCall
          type: ON_CALL
          url: https://onefootball.app.opsgenie.com/settings/schedule/detail/191b6b6d-f7eb-4a88-977e-bcc12f38b1b9
    documents:
        - id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:document/4d010f50-96c4-48c0-bab5-a3dd5112b464/6ef0a432-9ee5-414a-836a-30dd0a754255
          title: Akamai integration
          type: Other
          documentationCategoryId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:documentation-category/4d010f50-96c4-48c0-bab5-a3dd5112b464/154bf547-86c3-4d30-a74e-e73569ae37f8
          url: https://github.com/motain/streaming-service/blob/main/docs/akamai.md
        - id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:document/4d010f50-96c4-48c0-bab5-a3dd5112b464/8fc1acfd-5ba1-4c5c-b23e-745cc052cf11
          title: Bitmovin integration
          type: Other
          documentationCategoryId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:documentation-category/4d010f50-96c4-48c0-bab5-a3dd5112b464/154bf547-86c3-4d30-a74e-e73569ae37f8
          url: https://github.com/motain/streaming-service/blob/main/docs/bitmovin.md
        - id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:document/4d010f50-96c4-48c0-bab5-a3dd5112b464/82653348-bdda-443b-8d2b-8b216c28d38f
          title: Home
          type: Other
          documentationCategoryId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:documentation-category/4d010f50-96c4-48c0-bab5-a3dd5112b464/154bf547-86c3-4d30-a74e-e73569ae37f8
          url: https://github.com/motain/streaming-service/blob/main/docs/index.md
        - id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:document/4d010f50-96c4-48c0-bab5-a3dd5112b464/d8f9bd62-3f80-461c-a1a6-07da184657c4
          title: Overview
          type: Other
          documentationCategoryId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:documentation-category/4d010f50-96c4-48c0-bab5-a3dd5112b464/154bf547-86c3-4d30-a74e-e73569ae37f8
          url: https://github.com/motain/streaming-service/blob/main/docs/overview.md
    labels:
        - live-video
        - streaming-service
        - engagement
    metricSources:
        critical-alerts-slo-check:
            id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-source/4d010f50-96c4-48c0-bab5-a3dd5112b464/b195dd6d-0c72-4c30-a00b-06b885596958
            name: critical-alerts-slo-check-svc-streaming-service
            metric: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/e44a9fe3-99a8-42cd-8fd2-01a34b6a5111
            facts:
                all:
                    - source: jsonapi
                      uri: https://api.eu1.honeycomb.io/1/slos/streaming-service
                      componentName: ""
                      name: has-slos
                      repo: ""
                      factType: jsonPath
                      filePath: ""
                      regexPattern: ""
                      jsonPath: length($.)
                      repoProperty: ""
                      reposSearchQuery: ""
                      expectedValue: ""
                      expectedFormula: '>= 1'
                      auth:
                        header: X-Honeycomb-Team
                        tokenEnvVariable: HONEYCOMB_API_KEY
                any: []
                inspect: null
        deployment-readiness:
            id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-source/4d010f50-96c4-48c0-bab5-a3dd5112b464/9b0e2ad6-ba3b-433c-a0ea-48c4c214df81
            name: deployment-readiness-svc-streaming-service
            metric: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/5a0691b1-7596-493c-9820-ddf493ae7f30
            facts:
                all:
                    - source: github
                      uri: ""
                      componentName: ""
                      name: apptoml-file-exists
                      repo: streaming-service
                      factType: fileExists
                      filePath: app.toml
                      regexPattern: ""
                      jsonPath: ""
                      repoProperty: ""
                      reposSearchQuery: ""
                      expectedValue: ""
                      expectedFormula: ""
                      auth: null
                any: []
                inspect: null
        instrumentation-check:
            id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-source/4d010f50-96c4-48c0-bab5-a3dd5112b464/566e513d-bbd1-454b-8388-62475f4b5fd6
            name: instrumentation-check-svc-streaming-service
            metric: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/ec651e45-d88f-41e4-b796-ef3edabf8489
            facts:
                all:
                    - source: github
                      uri: ""
                      componentName: ""
                      name: app-toml-envs-otel-service-name
                      repo: streaming-service
                      factType: jsonPath
                      filePath: app.toml
                      regexPattern: ""
                      jsonPath: $..envs..OTEL_SERVICE_NAME
                      repoProperty: ""
                      reposSearchQuery: ""
                      expectedValue: streaming-service
                      expectedFormula: ""
                      auth: null
                any:
                    - source: github
                      uri: ""
                      componentName: ""
                      name: app-toml-env-otel-resource-attributes-sample-rate
                      repo: streaming-service
                      factType: jsonPath
                      filePath: app.toml
                      regexPattern: ""
                      jsonPath: $..envs..OTEL_RESOURCE_ATTRIBUTES
                      repoProperty: ""
                      reposSearchQuery: ""
                      expectedValue: of\.sample_rate=\d+.*
                      expectedFormula: ""
                      auth: null
                    - source: github
                      uri: ""
                      componentName: ""
                      name: app-toml-env-otel-resource-attributes-error-sample-rate
                      repo: streaming-service
                      factType: jsonPath
                      filePath: app.toml
                      regexPattern: ""
                      jsonPath: $..envs..OTEL_RESOURCE_ATTRIBUTES
                      repoProperty: ""
                      reposSearchQuery: ""
                      expectedValue: of\.error_sample_rate=\d+.*
                      expectedFormula: ""
                      auth: null
                inspect: null
        organizational-standards:
            id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-source/4d010f50-96c4-48c0-bab5-a3dd5112b464/5b6f63ab-9346-4120-b43b-ff132caf4411
            name: organizational-standards-svc-streaming-service
            metric: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/840c34a5-94f5-4411-b172-4af871317eb7
            facts:
                all:
                    - source: github
                      uri: ""
                      componentName: ""
                      name: app-toml-catalog-links-runbook
                      repo: streaming-service
                      factType: jsonPath
                      filePath: app.toml
                      regexPattern: ""
                      jsonPath: length($..catalog.links[?(@.type == 'DOCUMENT' && @.name == 'runbook')].url)
                      repoProperty: ""
                      reposSearchQuery: ""
                      expectedValue: ""
                      expectedFormula: == 1
                      auth: null
                    - source: github
                      uri: ""
                      componentName: ""
                      name: readme-file-exists
                      repo: streaming-service
                      factType: fileExists
                      filePath: README.md
                      regexPattern: ""
                      jsonPath: ""
                      repoProperty: ""
                      reposSearchQuery: ""
                      expectedValue: ""
                      expectedFormula: ""
                      auth: null
                any: []
                inspect: null
    tribe: engagement
    squad: live-video
---
apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: ott-external-accounts
    componentType: service
spec:
    id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:component/4d010f50-96c4-48c0-bab5-a3dd5112b464/f8021842-6251-4ec2-8c30-d37dd332a2df
    name: ott-external-accounts
    slug: svc-ott-external-accounts
    description: ""
    configVersion: 0
    typeId: SERVICE
    ownerId: ari:cloud:identity::team/a1604116-f750-4bb3-a850-800958ce934a
    dependsOn: []
    links:
        - id: f4c91abe-f17c-4e18-927f-4d8100435dda
          name: Live Video
          type: PROJECT
          url: https://onefootball.atlassian.net/jira/software/projects/LIVEVIDEO/boards/300
        - id: 2bafe00e-7ce4-4347-95af-9a3bbd38b9c1
          name: Repository
          type: REPOSITORY
          url: https://github.com/motain/ott-external-accounts
        - id: 4bcaf0b3-6256-4de1-9933-3f89c980256c
          name: Monitoring page
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=ott-external-accounts&var-container=ott-external-accounts&from=now-1h&to=now
        - id: a2df2a11-6a29-4274-b369-24e58ee5f00f
          name: OnCall
          type: ON_CALL
          url: https://onefootball.app.opsgenie.com/settings/schedule/detail/191b6b6d-f7eb-4a88-977e-bcc12f38b1b9
        - id: 9f219800-2f0a-4631-955d-7733a9960fd7
          name: e-livevideo
          type: CHAT_CHANNEL
          url: https://onefootball.slack.com/archives/C053ATVH3N2
    documents: []
    labels:
        - ott
        - live-video
    metricSources:
        critical-alerts-slo-check:
            id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-source/4d010f50-96c4-48c0-bab5-a3dd5112b464/62f96911-d366-454e-af70-8647a3446219
            name: critical-alerts-slo-check-svc-ott-external-accounts
            metric: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/e44a9fe3-99a8-42cd-8fd2-01a34b6a5111
            facts:
                all:
                    - source: jsonapi
                      uri: https://api.eu1.honeycomb.io/1/slos/ott-external-accounts
                      componentName: ""
                      name: has-slos
                      repo: ""
                      factType: jsonPath
                      filePath: ""
                      regexPattern: ""
                      jsonPath: length($.)
                      repoProperty: ""
                      reposSearchQuery: ""
                      expectedValue: ""
                      expectedFormula: '>= 1'
                      auth:
                        header: X-Honeycomb-Team
                        tokenEnvVariable: HONEYCOMB_API_KEY
                any: []
                inspect: null
        deployment-readiness:
            id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-source/4d010f50-96c4-48c0-bab5-a3dd5112b464/dcc7e6df-8b34-4088-81d5-fddd0b9985dd
            name: deployment-readiness-svc-ott-external-accounts
            metric: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/5a0691b1-7596-493c-9820-ddf493ae7f30
            facts:
                all:
                    - source: github
                      uri: ""
                      componentName: ""
                      name: apptoml-file-exists
                      repo: ott-external-accounts
                      factType: fileExists
                      filePath: app.toml
                      regexPattern: ""
                      jsonPath: ""
                      repoProperty: ""
                      reposSearchQuery: ""
                      expectedValue: ""
                      expectedFormula: ""
                      auth: null
                any: []
                inspect: null
        instrumentation-check:
            id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-source/4d010f50-96c4-48c0-bab5-a3dd5112b464/66b04bf2-fa3f-43e8-a24c-89498ed23e5c
            name: instrumentation-check-svc-ott-external-accounts
            metric: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/ec651e45-d88f-41e4-b796-ef3edabf8489
            facts:
                all:
                    - source: github
                      uri: ""
                      componentName: ""
                      name: app-toml-envs-otel-service-name
                      repo: ott-external-accounts
                      factType: jsonPath
                      filePath: app.toml
                      regexPattern: ""
                      jsonPath: $..envs..OTEL_SERVICE_NAME
                      repoProperty: ""
                      reposSearchQuery: ""
                      expectedValue: ott-external-accounts
                      expectedFormula: ""
                      auth: null
                any:
                    - source: github
                      uri: ""
                      componentName: ""
                      name: app-toml-env-otel-resource-attributes-sample-rate
                      repo: ott-external-accounts
                      factType: jsonPath
                      filePath: app.toml
                      regexPattern: ""
                      jsonPath: $..envs..OTEL_RESOURCE_ATTRIBUTES
                      repoProperty: ""
                      reposSearchQuery: ""
                      expectedValue: of\.sample_rate=\d+.*
                      expectedFormula: ""
                      auth: null
                    - source: github
                      uri: ""
                      componentName: ""
                      name: app-toml-env-otel-resource-attributes-error-sample-rate
                      repo: ott-external-accounts
                      factType: jsonPath
                      filePath: app.toml
                      regexPattern: ""
                      jsonPath: $..envs..OTEL_RESOURCE_ATTRIBUTES
                      repoProperty: ""
                      reposSearchQuery: ""
                      expectedValue: of\.error_sample_rate=\d+.*
                      expectedFormula: ""
                      auth: null
                inspect: null
        organizational-standards:
            id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-source/4d010f50-96c4-48c0-bab5-a3dd5112b464/3207ec53-1f71-4b03-964e-f963634bee3e
            name: organizational-standards-svc-ott-external-accounts
            metric: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/840c34a5-94f5-4411-b172-4af871317eb7
            facts:
                all:
                    - source: github
                      uri: ""
                      componentName: ""
                      name: app-toml-catalog-links-runbook
                      repo: ott-external-accounts
                      factType: jsonPath
                      filePath: app.toml
                      regexPattern: ""
                      jsonPath: length($..catalog.links[?(@.type == 'DOCUMENT' && @.name == 'runbook')].url)
                      repoProperty: ""
                      reposSearchQuery: ""
                      expectedValue: ""
                      expectedFormula: == 1
                      auth: null
                    - source: github
                      uri: ""
                      componentName: ""
                      name: readme-file-exists
                      repo: ott-external-accounts
                      factType: fileExists
                      filePath: README.md
                      regexPattern: ""
                      jsonPath: ""
                      repoProperty: ""
                      reposSearchQuery: ""
                      expectedValue: ""
                      expectedFormula: ""
                      auth: null
                any: []
                inspect: null
    tribe: ott
    squad: live-video
