apiVersion: of-catalog/v1alpha1
kind: Metric
metadata:
    name: instrumentation-check
    labels:
        grading-system: observability
    componentType:
        - service
        - cloud-resource
    facts:
        all:
            - source: github
              uri: ""
              componentName: ""
              name: app-toml-envs-otel-service-name
              repo: ${Metadata.Name}
              factType: jsonPath
              filePath: app.toml
              regexPattern: ""
              jsonPath: $..envs..OTEL_SERVICE_NAME
              repoProperty: ""
              reposSearchQuery: ""
              expectedValue: ${Metadata.Name}
              expectedFormula: ""
              auth: null
        any:
            - source: github
              uri: ""
              componentName: ""
              name: app-toml-env-otel-resource-attributes-sample-rate
              repo: ${Metadata.Name}
              factType: jsonPath
              filePath: app.toml
              regexPattern: ""
              jsonPath: $..envs..OTEL_RESOURCE_ATTRIBUTES
              repoProperty: ""
              reposSearchQuery: ""
              expectedValue: of\.sample_rate=\d+.*
              expectedFormula: ""
              auth: null
            - source: github
              uri: ""
              componentName: ""
              name: app-toml-env-otel-resource-attributes-error-sample-rate
              repo: ${Metadata.Name}
              factType: jsonPath
              filePath: app.toml
              regexPattern: ""
              jsonPath: $..envs..OTEL_RESOURCE_ATTRIBUTES
              repoProperty: ""
              reposSearchQuery: ""
              expectedValue: of\.error_sample_rate=\d+.*
              expectedFormula: ""
              auth: null
        inspect: null
spec:
    id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/ec651e45-d88f-41e4-b796-ef3edabf8489
    name: instrumentation-check
    description: Verifies that the component is set up to record relevant telemetry (metrics or traces).
    format:
        unit: Instrumentation Check
---
apiVersion: of-catalog/v1alpha1
kind: Metric
metadata:
    name: critical-alerts-slo-check
    labels:
        grading-system: observability
    componentType:
        - service
    facts:
        all:
            - source: jsonapi
              uri: https://api.eu1.honeycomb.io/1/slos/${Metadata.Name}
              componentName: ""
              name: has-slos
              repo: ""
              factType: jsonPath
              filePath: ""
              regexPattern: ""
              jsonPath: length($.)
              repoProperty: ""
              reposSearchQuery: ""
              expectedValue: ""
              expectedFormula: '>= 1'
              auth:
                header: X-Honeycomb-Team
                tokenEnvVariable: HONEYCOMB_API_KEY
        any: []
        inspect: null
spec:
    id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/e44a9fe3-99a8-42cd-8fd2-01a34b6a5111
    name: critical-alerts-slo-check
    description: Checks if at least one critical performance or reliability metric is actively monitored and triggers an alert (e.g., SLO or metric threshold).
    format:
        unit: Critical Alerts/SLO Check
---
apiVersion: of-catalog/v1alpha1
kind: Metric
metadata:
    name: organizational-standards
    labels:
        grading-system: production-readiness
    componentType:
        - service
        - cloud-resource
    facts:
        all:
            - source: github
              uri: ""
              componentName: ""
              name: app-toml-catalog-links-runbook
              repo: ${Metadata.Name}
              factType: jsonPath
              filePath: app.toml
              regexPattern: ""
              jsonPath: length($..catalog.links[?(@.type == 'DOCUMENT' && @.name == 'runbook')].url)
              repoProperty: ""
              reposSearchQuery: ""
              expectedValue: ""
              expectedFormula: == 1
              auth: null
            - source: github
              uri: ""
              componentName: ""
              name: readme-file-exists
              repo: ${Metadata.Name}
              factType: fileExists
              filePath: README.md
              regexPattern: ""
              jsonPath: ""
              repoProperty: ""
              reposSearchQuery: ""
              expectedValue: ""
              expectedFormula: ""
              auth: null
        any: []
        inspect: null
spec:
    id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/840c34a5-94f5-4411-b172-4af871317eb7
    name: organizational-standards
    description: Ensures the component is correctly configured, adheres to best practices, and meets all necessary requirements for secure, stable, and efficient deployment in a production environment.
    format:
        unit: Organizational Standards
---
apiVersion: of-catalog/v1alpha1
kind: Metric
metadata:
    name: deployment-readiness
    labels:
        grading-system: production-readiness
    componentType:
        - service
        - cloud-resource
    facts:
        all:
            - source: github
              uri: ""
              componentName: ""
              name: apptoml-file-exists
              repo: ${Metadata.Name}
              factType: fileExists
              filePath: app.toml
              regexPattern: ""
              jsonPath: ""
              repoProperty: ""
              reposSearchQuery: ""
              expectedValue: ""
              expectedFormula: ""
              auth: null
        any: []
        inspect: null
spec:
    id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/5a0691b1-7596-493c-9820-ddf493ae7f30
    name: deployment-readiness
    description: Ensures the component is correctly configured, adheres to best practices, and meets all necessary requirements for secure, stable, and efficient deployment in a production environment.
    format:
        unit: Deployment Readiness
