apiVersion: of-catalog/v1alpha1
kind: Scorecard
metadata:
    name: cost-optimization
spec:
    id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:scorecard/4d010f50-96c4-48c0-bab5-a3dd5112b464/60e4a503-1fc1-4626-a216-6a41dfae7747
    name: cost-optimization
    description: https://github.com/motain/of-catalog/blob/main/docs/grading-system/cost-optimization.md#cost-optimization-grading-system
    ownerId: 712020:edcf2690-1f3e-4310-9eb8-1ecef88d64b6
    state: PUBLISHED
    componentTypeIds:
        - SERVICE
    importance: REQUIRED
    scoringStrategyType: WEIGHT_BASED
    criteria:
        - hasMetricValue:
            id: 60169781-28b8-40a9-8a6c-0981f31cae67
            weight: 100
            name: allocation-efficiency
            metricName: allocation-efficiency
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/0280d248-c53a-4dcf-a5a4-945cdd931406
            comparatorValue: 1
            comparator: EQUALS
---
apiVersion: of-catalog/v1alpha1
kind: Scorecard
metadata:
    name: observability
spec:
    id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:scorecard/4d010f50-96c4-48c0-bab5-a3dd5112b464/9898047d-9310-4ec4-a920-8dd740d6cf39
    name: observability
    description: https://github.com/motain/of-catalog/blob/main/docs/grading-system/observability.md#observability-grading-system
    ownerId: 712020:edcf2690-1f3e-4310-9eb8-1ecef88d64b6
    state: PUBLISHED
    componentTypeIds:
        - SERVICE
    importance: REQUIRED
    scoringStrategyType: WEIGHT_BASED
    criteria:
        - hasMetricValue:
            id: d683cca2-1e0f-41f7-bc20-98bbaf80bff5
            weight: 15
            name: instrumentation-check
            metricName: instrumentation-check
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/be5dd5aa-9468-4dd1-8e7a-580b9da4e5c6
            comparatorValue: 1
            comparator: EQUALS
        - hasMetricValue:
            id: 5ec3f2ea-c7c4-429c-b62d-1fe93512862e
            weight: 15
            name: critical-alerts-slo-check
            metricName: critical-alerts-slo-check
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/80249b35-572f-41be-9f7d-78d7ca793029
            comparatorValue: 1
            comparator: EQUALS
        - hasMetricValue:
            id: cd39e584-f33e-4f7c-85e5-a5c003aef342
            weight: 45
            name: alert-routing-and-notifications
            metricName: alert-routing-and-notifications
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/a475e853-8c43-47af-8b94-99240e853480
            comparatorValue: 1
            comparator: EQUALS
        - hasMetricValue:
            id: cc5ab930-dd32-41d4-803b-e655a8fad5b9
            weight: 25
            name: observability-documentation
            metricName: observability-documentation
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/f133b6d9-595f-4862-a10d-cb356968e2bc
            comparatorValue: 1
            comparator: EQUALS
---
apiVersion: of-catalog/v1alpha1
kind: Scorecard
metadata:
    name: production-readiness
spec:
    id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:scorecard/4d010f50-96c4-48c0-bab5-a3dd5112b464/09359de9-1a80-48d6-bd5d-60a236c7a18b
    name: production-readiness
    description: https://github.com/motain/of-catalog/blob/main/docs/grading-system/production-readiness.md#production-readiness-grading-system
    ownerId: 712020:edcf2690-1f3e-4310-9eb8-1ecef88d64b6
    state: PUBLISHED
    componentTypeIds:
        - SERVICE
    importance: REQUIRED
    scoringStrategyType: WEIGHT_BASED
    criteria:
        - hasMetricValue:
            id: 8f624c81-e107-4a5e-bcfb-45b2b981ec54
            weight: 50
            name: organizational-standards
            metricName: organizational-standards
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/557a1209-6a66-4eda-8051-9634991b75f2
            comparatorValue: 1
            comparator: EQUALS
        - hasMetricValue:
            id: 0c23d568-cc35-49f3-b539-751896c0d465
            weight: 50
            name: deployment-readiness
            metricName: deployment-readiness
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/e9c34910-156e-4669-b283-3d3bb08c58ac
            comparatorValue: 1
            comparator: EQUALS
---
apiVersion: of-catalog/v1alpha1
kind: Scorecard
metadata:
    name: resiliency
spec:
    id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:scorecard/4d010f50-96c4-48c0-bab5-a3dd5112b464/ef175b13-4017-47e6-94c0-d6a9b06628f4
    name: resiliency
    description: https://github.com/motain/of-catalog/blob/main/docs/grading-system/resiliency.md#resiliency-grading-system
    ownerId: 712020:edcf2690-1f3e-4310-9eb8-1ecef88d64b6
    state: PUBLISHED
    componentTypeIds:
        - SERVICE
    importance: REQUIRED
    scoringStrategyType: WEIGHT_BASED
    criteria:
        - hasMetricValue:
            id: 134b83ea-3527-4b79-8760-420500b12685
            weight: 50
            name: high-availability
            metricName: high-availability
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/43e2c6ef-1a41-4fd6-b0e9-d7d7545681fd
            comparatorValue: 1
            comparator: EQUALS
        - hasMetricValue:
            id: c2c66206-b925-4fb5-a271-c0f121d6a203
            weight: 50
            name: adaptive-systems
            metricName: adaptive-systems
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/d6af0782-90a4-44e6-a9e9-4535573bd716
            comparatorValue: 1
            comparator: EQUALS
---
apiVersion: of-catalog/v1alpha1
kind: Scorecard
metadata:
    name: security
spec:
    id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:scorecard/4d010f50-96c4-48c0-bab5-a3dd5112b464/1b511a02-0163-435a-9aae-94a13d9fdd21
    name: security
    description: https://github.com/motain/of-catalog/blob/main/docs/grading-system/security.md#security-grading-system
    ownerId: 712020:edcf2690-1f3e-4310-9eb8-1ecef88d64b6
    state: PUBLISHED
    componentTypeIds:
        - SERVICE
    importance: REQUIRED
    scoringStrategyType: WEIGHT_BASED
    criteria:
        - hasMetricValue:
            id: 0fe30f03-ef06-4829-beed-8cca028cdf5a
            weight: 50
            name: security-as-pipeline
            metricName: security-as-pipeline
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/f16a5dad-816a-48db-9e96-6d1250e63659
            comparatorValue: 1
            comparator: EQUALS
        - hasMetricValue:
            id: 70a249dd-a8a0-4ecd-bd0a-604d618010a3
            weight: 50
            name: vulnerability-management
            metricName: vulnerability-management
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/6390dfc8-c94e-492a-8741-3fcbfa2fbddb
            comparatorValue: 1
            comparator: LESS_THAN
