apiVersion: of-catalog/v1alpha1
kind: Scorecard
metadata:
    name: production-readiness
spec:
    id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:scorecard/4d010f50-96c4-48c0-bab5-a3dd5112b464/8ec1e41d-03c0-4935-bb47-5df714f6493e
    name: production-readiness
    description: 'Guidelines to ensure that the service is ready for production. For details: https://onefootball.atlassian.net/wiki/spaces/CORE/pages/4908318721/Production+Readiness+Grading+system'
    ownerId: 712020:edcf2690-1f3e-4310-9eb8-1ecef88d64b6
    state: PUBLISHED
    componentTypeIds:
        - SERVICE
    importance: REQUIRED
    scoringStrategyType: WEIGHT_BASED
    criteria:
        - hasMetricValue:
            id: ""
            weight: 50
            name: organizational-standards
            metricName: organizational-standards
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/005d1bf2-7188-4682-861b-a1f8bb7043ed
            comparatorValue: 1
            comparator: EQUALS
        - hasMetricValue:
            id: ""
            weight: 50
            name: deployment-readiness
            metricName: deployment-readiness
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/ef2ef7b8-cc47-4f67-84d3-ba9bebef1ba8
            comparatorValue: 1
            comparator: EQUALS
---
apiVersion: of-catalog/v1alpha1
kind: Scorecard
metadata:
    name: resiliency
spec:
    id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:scorecard/4d010f50-96c4-48c0-bab5-a3dd5112b464/f691cd08-83fa-42de-9821-37a79ea192fb
    name: resiliency
    description: 'Guidelines to ensure that the service is ready for production. For details: https://onefootball.atlassian.net/wiki/spaces/CORE/pages/4908056637/Resiliency+Grading+System'
    ownerId: 712020:edcf2690-1f3e-4310-9eb8-1ecef88d64b6
    state: PUBLISHED
    componentTypeIds:
        - SERVICE
    importance: REQUIRED
    scoringStrategyType: WEIGHT_BASED
    criteria:
        - hasMetricValue:
            id: ""
            weight: 50
            name: high-availability
            metricName: high-availability
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/739d09e9-de03-426c-b82e-15e7aeb385b4
            comparatorValue: 1
            comparator: EQUALS
        - hasMetricValue:
            id: ""
            weight: 50
            name: adaptive-systems
            metricName: adaptive-systems
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/0f72a9b2-c7f2-4eff-b905-1e715c3a8810
            comparatorValue: 1
            comparator: EQUALS
---
apiVersion: of-catalog/v1alpha1
kind: Scorecard
metadata:
    name: cost-optimization
spec:
    id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:scorecard/4d010f50-96c4-48c0-bab5-a3dd5112b464/fe61a807-6bf9-4134-b9f9-27da261fa13f
    name: cost-optimization
    description: Guidelines to ensure that the service is ready for cost Optimized. https://onefootball.atlassian.net/wiki/spaces/CORE/pages/4908154881/Cost+Optimization+Grading+system
    ownerId: 712020:edcf2690-1f3e-4310-9eb8-1ecef88d64b6
    state: PUBLISHED
    componentTypeIds:
        - SERVICE
    importance: REQUIRED
    scoringStrategyType: WEIGHT_BASED
    criteria:
        - hasMetricValue:
            id: ""
            weight: 100
            name: allocation-efficiency
            metricName: allocation-efficiency
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/223be0f4-d7bb-4254-9529-e77aa497e798
            comparatorValue: 1
            comparator: EQUALS
---
apiVersion: of-catalog/v1alpha1
kind: Scorecard
metadata:
    name: observability
spec:
    id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:scorecard/4d010f50-96c4-48c0-bab5-a3dd5112b464/7919d4d5-4564-4b25-9f44-773b1d6595e8
    name: observability
    description: 'Guidelines to ensure that the service is observable. For details: https://onefootball.atlassian.net/wiki/spaces/CORE/pages/4853530681/Observability+Grading+System'
    ownerId: 712020:edcf2690-1f3e-4310-9eb8-1ecef88d64b6
    state: PUBLISHED
    componentTypeIds:
        - SERVICE
    importance: REQUIRED
    scoringStrategyType: WEIGHT_BASED
    criteria:
        - hasMetricValue:
            id: ""
            weight: 30
            name: instrumentation-check
            metricName: instrumentation-check
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/71dfd551-e995-4092-ab06-e2718e75641e
            comparatorValue: 1
            comparator: EQUALS
        - hasMetricValue:
            id: ""
            weight: 40
            name: critical-alerts-slo-check
            metricName: critical-alerts-slo-check
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/a2523e39-c11a-4449-8465-f41613881b22
            comparatorValue: 1
            comparator: EQUALS
        - hasMetricValue:
            id: ""
            weight: 15
            name: alert-routing-and-notifications
            metricName: alert-routing-and-notifications
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/9a068e9d-a760-4928-a092-e626128aeeb0
            comparatorValue: 1
            comparator: EQUALS
        - hasMetricValue:
            id: ""
            weight: 15
            name: observability-documentation
            metricName: observability-documentation
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/c5f96c3d-6845-4155-9576-62f86725b07f
            comparatorValue: 1
            comparator: EQUALS
---
apiVersion: of-catalog/v1alpha1
kind: Scorecard
metadata:
    name: security
spec:
    id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:scorecard/4d010f50-96c4-48c0-bab5-a3dd5112b464/cae16370-80c1-4e74-98a3-24e7f90014c9
    name: security
    description: SECURITY Grading system
    ownerId: 712020:edcf2690-1f3e-4310-9eb8-1ecef88d64b6
    state: PUBLISHED
    componentTypeIds:
        - SERVICE
    importance: REQUIRED
    scoringStrategyType: WEIGHT_BASED
    criteria:
        - hasMetricValue:
            id: bbf5759d-26d2-4e3b-89bd-190a32da2ae1
            weight: 50
            name: security-as-pipeline
            metricName: security-as-pipeline
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/295e70fa-9359-4a0f-9188-6f7b6a0dbd7e
            comparatorValue: 1
            comparator: EQUALS
        - hasMetricValue:
            id: ""
            weight: 50
            name: vulnerability-management
            metricName: vulnerability-management
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/5c7562aa-6b71-4deb-911f-eebac354ee3e
            comparatorValue: 1
            comparator: LESS_THAN
