---
apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: 'loyalty-service'
    componentType: service
spec:
    tribe: membership
    squad: onefootball-club
    name: loyalty-service
    slug: svc-loyalty-service
    description: Not Provided
    ownerId: ""
    typeId: SERVICE
    dependsOn:
        - kubernetes
    fields:
        lifecycle: Active
        tier: 4
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/loyalty-service
        - name: Prometheus Resource Metrics
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=loyalty-service&var-container=loyalty-service&from=now-1h&to=now
        - name: OnCall
          type: ON_CALL
          url: https://onefootball.app.opsgenie.com/settings/schedule/detail/191b6b6d-f7eb-4a88-977e-bcc12f38b1b9
        - name: Emissary Metrics
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/z387xeWVk/ambassador-emissary-ingress?var-window=1m&orgId=1&from=now-30m&to=now&timezone=browser&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-SERVICE=loyalty_service_loyalty_service_svc_cluster_local_&refresh=5s
        - name: onefootball-club
          type: CHAT_CHANNEL
          url: https://onefootball.slack.com/archives/C05R46W1TMZ
        - name: OFC
          type: PROJECT
          url: https://onefootball.atlassian.net/jira/software/projects/LOYAL/boards/393/backlog
    labels:
        - onefootball-club
        - membership
    customFields: null
