apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: push-notification-center
    componentType: service
spec:
    name: push-notification-center
    slug: svc-push-notification-center
    description: ""
    configVersion: 1
    typeId: SERVICE
    ownerId: ""
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/push-notification-center
        - name: Monitoring page
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=push-notification-center&var-container=push-notification-center&from=now-1h&to=now
    labels:
        - reach
        - content
