apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: web-experience
    componentType: service
spec:
    name: web-experience
    slug: ""
    description: ""
    typeId: SERVICE
    ownerId: ""
    dependsOn:
        - search-gateway-api
        - userresearch-shiny
    tribe: reach
    squad: consumer-web
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/web-experience
        - name: Monitoring page
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=web-experience&var-container=web-experience&from=now-1h&to=now
    labels:
        - consumer-web
        - reach
