---
apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: 'web-payments-backend'
    componentType: service
spec:
    tribe: ott
    squad: live-video
    name: web-payments-backend
    slug: svc-web-payments-backend
    description: ""
    ownerId: ""
    typeId: SERVICE
    dependsOn:
        - kubernetes
        - watch
        - users-accounts-api
    fields:
        lifecycle: Active
        tier: 3
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/web-payments-backend
        - name: Prometheus Resource Metrics
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=web-payments-backend&var-container=web-payments-backend&from=now-1h&to=now
        - name: OnCall
          type: ON_CALL
          url: https://onefootball.app.opsgenie.com/settings/schedule/detail/191b6b6d-f7eb-4a88-977e-bcc12f38b1b9
        - name: Emissary Metrics
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/z387xeWVk/ambassador-emissary-ingress?var-window=1m&orgId=1&from=now-30m&to=now&timezone=browser&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-SERVICE=web_payments_backend_web_payments_backend_svc_cluster_local_&refresh=5s
        - name: e-livevideo
          type: CHAT_CHANNEL
          url: https://onefootball.slack.com/archives/C053ATVH3N2
        - name: Live Video
          type: PROJECT
          url: https://onefootball.atlassian.net/jira/software/projects/LIVEVIDEO/boards/300
    labels:
        - of-catalog
        - live-video
        - ott
    customFields: null
