apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: fanmatch-go
    componentType: service
spec:
    name: fanmatch-go
    slug: ""
    description: ""
    typeId: SERVICE
    ownerId: ""
    dependsOn: []
    tribe: monetization
    squad: sponsorship-integration
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/fanmatch-go
        - name: Monitoring page
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=fanmatch-go&var-container=fanmatch-go&from=now-1h&to=now
    labels:
        - monetization
        - sponsorship-integration
        - fanmatch-go
