apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: article-translator
    componentType: service
spec:
    name: article-translator
    slug: ""
    description: ""
    typeId: SERVICE
    ownerId: ""
    dependsOn: []
    tribe: fan-experience
    squad: source
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/article-translator
        - name: Prometheus Resource Metrics
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=article-translator&var-container=article-translator&from=now-1h&to=now
        - name: Emissary Metrics
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/z387xeWVk/ambassador-emissary-ingress?var-window=1m&orgId=1&from=now-30m&to=now&timezone=browser&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-SERVICE=article_translator_article_translator_svc_cluster_local_&refresh=5s
        - name: OnCall
          type: ON_CALL
          url: https://onefootball.app.opsgenie.com/settings/schedule/detail/191b6b6d-f7eb-4a88-977e-bcc12f38b1b9
    labels:
        - fan-experience
        - source
        - article-translator
