apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: follower-count-publisher
    componentType: service
spec:
    name: follower-count-publisher
    slug: svc-follower-count-publisher
    description: ""
    typeId: SERVICE
    ownerId: ""
    tribe: engagement
    squad: matchxp
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/follower-count-publisher
        - name: Monitoring page
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=follower-count-publisher&var-container=follower-count-publisher&from=now-1h&to=now
    labels:
        - matchxp
        - engagement
