apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: ott-external-accounts
    componentType: service
spec:
    name: ott-external-accounts
    slug: svc-ott-external-accounts
    description: ""
    configVersion: 1
    typeId: SERVICE
    ownerId: ""
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/ott-external-accounts
        - name: Monitoring page
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=ott-external-accounts&var-container=ott-external-accounts&from=now-1h&to=now
    labels:
        - live-video
        - ott
