apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: lead-gen-campaign-manager
    componentType: service
spec:
    name: lead-gen-campaign-manager
    slug: svc-lead-gen-campaign-manager
    description: ""
    configVersion: 1
    typeId: SERVICE
    ownerId: ""
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/lead-gen-campaign-manager
        - name: Monitoring page
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=lead-gen-campaign-manager&var-container=lead-gen-campaign-manager&from=now-1h&to=now
    labels:
        - monetization
        - sponsorship-integration
        - lead-gen-campaign-manager
