---
apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: 'cloud-runtime-bot'
    componentType: service
spec:
    tribe: platform
    squad: cloud-runtime
    name: cloud-runtime-bot
    slug: svc-cloud-runtime-bot
    description: ""
    ownerId: ""
    typeId: SERVICE
    dependsOn:
        - kubernetes
    fields:
        lifecycle: Active
        tier: 4
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/cloud-runtime-bot
        - name: Prometheus Resource Metrics
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=cloud-runtime-bot&var-container=cloud-runtime-bot&from=now-1h&to=now
        - name: OnCall
          type: ON_CALL
          url: https://onefootball.app.opsgenie.com/settings/schedule/detail/191b6b6d-f7eb-4a88-977e-bcc12f38b1b9
        - name: Emissary Metrics
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/z387xeWVk/ambassador-emissary-ingress?var-window=1m&orgId=1&from=now-30m&to=now&timezone=browser&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-SERVICE=cloud_runtime_bot_cloud_runtime_bot_svc_cluster_local_&refresh=5s
        - name: p-cloud-runtime
          type: CHAT_CHANNEL
          url: https://onefootball.slack.com/archives/CFUCQUA04
        - name: Cloud Runtime
          type: PROJECT
          url: https://onefootball.atlassian.net/jira/software/projects/CORE/boards/185
    labels:
        - cloud-runtime
        - platform
    customFields: null
