---
apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: 'tv-guide-importer'
    componentType: service
spec:
    name: tv-guide-importer
    slug: svc-tv-guide-importer
    description: Not Provided
    ownerId: ari:cloud:identity::team/f4797497-61c0-4312-93f3-8d0f31ace225
    typeId: SERVICE
    dependsOn:
        - resolver-api
    fields:
        lifecycle: Active
        tier: 4
        version: 'v1.0.14'
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/tv-guide-importer
        - name: Monitoring page
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=tv-guide-importer&var-container=tv-guide-importer&from=now-1h&to=now
        - name: OnCall
          type: ON_CALL
          url: https://onefootball.app.opsgenie.com/settings/schedule/detail/191b6b6d-f7eb-4a88-977e-bcc12f38b1b9
        - name: client-xp
          type: CHAT_CHANNEL
          url: https://onefootball.slack.com/archives/C07MMBZDYV6
        - name: Sponsorship Integration Squad
          type: PROJECT
          url: https://onefootball.atlassian.net/jira/software/projects/SIS/boards/378/backlog
    labels:
        - sponsorship-integration
        - client-experience
    customFields: null
