apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: experimental-thumbor
    componentType: service
spec:
    name: experimental-thumbor
    slug: svc-experimental-thumbor
    description: ""
    typeId: SERVICE
    ownerId: ""
    tribe: platform
    squad: developer-xp
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/experimental-thumbor
        - name: Monitoring page
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=experimental-thumbor&var-container=experimental-thumbor&from=now-1h&to=now
    labels:
        - platform
        - developer-xp
