apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: entity-service
    componentType: service
spec:
    name: entity-service
    slug: svc-entity-service
    description: ""
    typeId: SERVICE
    ownerId: ""
    tribe: engagement
    squad: matchxp
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/entity-service
        - name: Monitoring page
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=entity-service&var-container=entity-service&from=now-1h&to=now
    labels:
        - matchxp
        - engagement
