apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: web-payments-backend
    componentType: service
spec:
    name: web-payments-backend
    slug: ""
    description: ""
    typeId: SERVICE
    ownerId: ""
    dependsOn:
        - watch
        - users-accounts-api
    tribe: engagement
    squad: live-video
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/web-payments-backend
        - name: Monitoring page
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=web-payments-backend&var-container=web-payments-backend&from=now-1h&to=now
    labels:
        - web-payments-backend
        - engagement
        - live-video
