---
apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: 'oncall-compensation'
    componentType: service
spec:
    name: oncall-compensation
    slug: svc-oncall-compensation
    description: Not Provided
    ownerId: ari:cloud:identity::team/f4797497-61c0-4312-93f3-8d0f31ace225
    typeId: SERVICE
    dependsOn:
        - Kubernetes
    fields:
        lifecycle: Active
        tier: 4
        version: '1.6.10'
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/oncall-compensation
        - name: Monitoring page
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=oncall-compensation&var-container=oncall-compensation&from=now-1h&to=now
        - name: OnCall
          type: ON_CALL
          url: https://onefootball.app.opsgenie.com/settings/schedule/detail/191b6b6d-f7eb-4a88-977e-bcc12f38b1b9
        - name: p-developer-xp
          type: CHAT_CHANNEL
          url: https://onefootball.slack.com/archives/C04NMNZC89L
        - name: Developer Experience
          type: PROJECT
          url: https://onefootball.atlassian.net/jira/software/projects/DX/boards/375
    labels:
        - developer-xp
        - platform
    customFields: null
