apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: clips-webhooks
    componentType: service
spec:
    name: clips-webhooks
    slug: ""
    description: ""
    typeId: SERVICE
    ownerId: ""
    dependsOn: []
    tribe: engagement
    squad: personalisation
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/clips-webhooks
        - name: Monitoring page
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=clips-webhooks&var-container=clips-webhooks&from=now-1h&to=now
    labels:
        - engagement
        - personalisation
        - clips-webhooks
