apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: prometheus-exporter
    componentType: service
spec:
    name: prometheus-exporter
    slug: svc-prometheus-exporter
    description: ""
    configVersion: 1
    typeId: SERVICE
    ownerId: ""
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/prometheus-exporter
        - name: Monitoring page
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=prometheus-exporter&var-container=prometheus-exporter&from=now-1h&to=now
    labels:
        - platform
        - cloud-runtime
