apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: banner-free
    componentType: service
spec:
    name: banner-free
    slug: ""
    description: ""
    typeId: SERVICE
    ownerId: ""
    dependsOn: []
    tribe: monetization
    squad: media-advertising
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/banner-free
        - name: Monitoring page
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=banner-free&var-container=banner-free&from=now-1h&to=now
    labels:
        - media-advertising
        - banner-free
        - monetization
