apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: loyalty-service
    componentType: service
spec:
    name: loyalty-service
    slug: svc-loyalty-service
    description: ""
    typeId: SERVICE
    ownerId: ""
    tribe: monetization
    squad: loyalty-program
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/loyalty-service
        - name: Monitoring page
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=loyalty-service&var-container=loyalty-service&from=now-1h&to=now
    labels:
        - loyalty-program
        - monetization
