apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: betting-api
    componentType: service
spec:
    name: betting-api
    slug: ""
    description: ""
    typeId: SERVICE
    ownerId: ""
    dependsOn:
        - mediation-api
    tribe: monetization
    squad: sponsorship-integration
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/betting-api
        - name: Monitoring page
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=betting-api&var-container=betting-api&from=now-1h&to=now
    labels:
        - betting-api
        - monetization
        - sponsorship-integration
