---
apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: 'fanmatch-go'
    componentType: service
spec:
    name: fanmatch-go
    slug: svc-fanmatch-go
    description: Not Provided
    ownerId: ari:cloud:identity::team/f4797497-61c0-4312-93f3-8d0f31ace225
    typeId: SERVICE
    dependsOn:
        - Kubernetes
    fields:
        lifecycle: Active
        tier: 4
        version: 'v0.0.51'
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/fanmatch-go
        - name: Monitoring page
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=fanmatch-go&var-container=fanmatch-go&from=now-1h&to=now
        - name: OnCall
          type: ON_CALL
          url: https://onefootball.app.opsgenie.com/settings/schedule/detail/191b6b6d-f7eb-4a88-977e-bcc12f38b1b9
        - name: client-xp
          type: CHAT_CHANNEL
          url: https://onefootball.slack.com/archives/C07MMBZDYV6
        - name: Sponsorship Integration Squad
          type: PROJECT
          url: https://onefootball.atlassian.net/jira/software/projects/SIS/boards/378/backlog
    labels:
        - sponsorship-integration
        - monetization
    customFields: null
