apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: streaming-service
    componentType: service
spec:
    name: streaming-service
    slug: ""
    description: ""
    typeId: SERVICE
    ownerId: ""
    dependsOn: []
    tribe: engagement
    squad: live-video
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/streaming-service
        - name: Monitoring page
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=streaming-service&var-container=streaming-service&from=now-1h&to=now
    labels:
        - engagement
        - live-video
        - streaming-service
