apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: airship-email
    componentType: service
spec:
    name: airship-email
    slug: ""
    description: ""
    typeId: SERVICE
    ownerId: ""
    dependsOn: []
    tribe: reach
    squad: fan-activation
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/airship-email
        - name: Monitoring page
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=airship-email&var-container=airship-email&from=now-1h&to=now
    labels:
        - reach
        - fan-activation
        - airship-email
