---
apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: 'quiz-api'
    componentType: service
spec:
    tribe: client-experience
    squad: sponsorship-integration
    name: quiz-api
    slug: svc-quiz-api
    description: ""
    ownerId: ""
    typeId: SERVICE
    dependsOn:
        - kubernetes
    fields:
        lifecycle: Active
        tier: 3
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/quiz-api
        - name: Prometheus Resource Metrics
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=quiz-api&var-container=quiz-api&from=now-1h&to=now
        - name: OnCall
          type: ON_CALL
          url: https://onefootball.app.opsgenie.com/settings/schedule/detail/191b6b6d-f7eb-4a88-977e-bcc12f38b1b9
        - name: Emissary Metrics
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/z387xeWVk/ambassador-emissary-ingress?var-window=1m&orgId=1&from=now-30m&to=now&timezone=browser&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-SERVICE=quiz_api_quiz_api_svc_cluster_local_&refresh=5s
        - name: client-xp
          type: CHAT_CHANNEL
          url: https://onefootball.slack.com/archives/C07MMBZDYV6
        - name: Sponsorship Integration Squad
          type: PROJECT
          url: https://onefootball.atlassian.net/jira/software/projects/SIS/boards/378/backlog
    labels:
        - sponsorship-integration
        - client-experience
    customFields: null
