apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: rich-push
    componentType: service
spec:
    name: rich-push
    slug: svc-rich-push
    description: ""
    typeId: SERVICE
    ownerId: ""
    tribe: monetization
    squad: sponsorship-integration
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/rich-push
        - name: Monitoring page
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=rich-push&var-container=rich-push&from=now-1h&to=now
    labels:
        - sponsorship-integration
        - rich-push
        - monetization
