apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: news
    componentType: service
spec:
    name: news
    slug: ""
    description: ""
    typeId: SERVICE
    ownerId: ""
    dependsOn:
        - bookmarks
        - score-api
        - mediation-api
        - ott-mediation
        - librarian
        - clips
        - personalisation-service
        - search-gateway-api
        - category-tiles
        - article-service
    tribe: engagement
    squad: personalisation
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/news
        - name: Monitoring page
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=news&var-container=news&from=now-1h&to=now
    labels:
        - engagement
        - personalisation
