apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: tv-guide-api
    componentType: service
spec:
    name: tv-guide-api
    slug: svc-tv-guide-api
    description: ""
    configVersion: 1
    typeId: SERVICE
    ownerId: ""
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/tv-guide-api
        - name: Monitoring page
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=tv-guide-api&var-container=tv-guide-api&from=now-1h&to=now
    labels:
        - sponsorship-integration
        - tv-guide-api
        - monetization
