---
apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: 'airship-email'
    componentType: service
spec:
    tribe: membership
    squad: fan-activation
    name: airship-email
    slug: svc-airship-email
    description: ""
    ownerId: ""
    typeId: SERVICE
    dependsOn:
        - kubernetes
    fields:
        lifecycle: Active
        tier: 3
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/airship-email
        - name: Prometheus Resource Metrics
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=airship-email&var-container=airship-email&from=now-1h&to=now
        - name: OnCall
          type: ON_CALL
          url: https://onefootball.app.opsgenie.com/settings/schedule/detail/191b6b6d-f7eb-4a88-977e-bcc12f38b1b9
        - name: Emissary Metrics
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/z387xeWVk/ambassador-emissary-ingress?var-window=1m&orgId=1&from=now-30m&to=now&timezone=browser&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-SERVICE=airship_email_airship_email_svc_cluster_local_&refresh=5s
        - name: Honeycomb
          type: DASHBOARD
          url: https://ui.eu1.honeycomb.io/onefootball/environments/production/datasets/airship-email/home?tab=traces
        - name: Security Vulnerability Report
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/ycwPj724k/trivy-operator-dashboard?orgId=1&from=now-24h&to=now&timezone=browser&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=airship-email
        - name: r-activation
          type: CHAT_CHANNEL
          url: https://onefootball.slack.com/archives/CK9LTN6DR
        - name: Activation Squad
          type: PROJECT
          url: https://onefootball.atlassian.net/jira/software/projects/AC/boards/376
    labels:
        - fan-activation
        - membership
    customFields: null
