---
apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: 'backstage'
    componentType: service
spec:
    tribe: platform
    squad: cloud-runtime
    name: backstage
    slug: svc-backstage
    description: ""
    ownerId: ""
    typeId: SERVICE
    dependsOn:
        - kubernetes
    fields:
        lifecycle: Active
        tier: 3
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/backstage
        - name: Prometheus Resource Metrics
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=backstage&var-container=backstage&from=now-1h&to=now
        - name: OnCall
          type: ON_CALL
          url: https://onefootball.app.opsgenie.com/settings/schedule/detail/191b6b6d-f7eb-4a88-977e-bcc12f38b1b9
        - name: Emissary Metrics
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/z387xeWVk/ambassador-emissary-ingress?var-window=1m&orgId=1&from=now-30m&to=now&timezone=browser&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-SERVICE=backstage_backstage_svc_cluster_local_&refresh=5s
        - name: Honeycomb
          type: DASHBOARD
          url: https://ui.eu1.honeycomb.io/onefootball/environments/production/datasets/backstage/home?tab=traces
        - name: Security Vulnerability Report
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/ycwPj724k/trivy-operator-dashboard?orgId=1&from=now-24h&to=now&timezone=browser&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=backstage
        - name: p-cloud-runtime
          type: CHAT_CHANNEL
          url: https://onefootball.slack.com/archives/CFUCQUA04
        - name: Cloud Runtime
          type: PROJECT
          url: https://onefootball.atlassian.net/jira/software/projects/CORE/boards/185
    labels:
        - cloud-runtime
        - platform
    customFields: null
