apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: web3-transactions
    componentType: service
spec:
    name: web3-transactions
    slug: svc-web3-transactions
    description: ""
    typeId: SERVICE
    ownerId: ""
    tribe: monetization
    squad: loyalty-program-squad
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/web3-transactions
        - name: Monitoring page
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=web3-transactions&var-container=web3-transactions&from=now-1h&to=now
    labels:
        - loyalty-program-squad
        - monetization
