---
apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: 'creators-network'
    componentType: service
spec:
    tribe: fan-experience
    squad: source
    name: creators-network
    slug: svc-creators-network
    description: Not Provided
    ownerId: ""
    typeId: SERVICE
    dependsOn:
        - kubernetes
    fields:
        lifecycle: Active
        tier: 4
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/creators-network
        - name: Monitoring page
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=creators-network&var-container=creators-network&from=now-1h&to=now
        - name: OnCall
          type: ON_CALL
          url: https://onefootball.app.opsgenie.com/settings/schedule/detail/191b6b6d-f7eb-4a88-977e-bcc12f38b1b9
        - name: r-source
          type: CHAT_CHANNEL
          url: https://onefootball.slack.com/archives/C055TBZP1B9
        - name: The Source
          type: PROJECT
          url: https://onefootball.atlassian.net/jira/software/projects/SRC/boards/200
    labels:
        - source
        - fan-experience
    customFields: null
