apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: funtik
    componentType: service
spec:
    name: funtik
    slug: svc-funtik
    description: ""
    typeId: SERVICE
    ownerId: ""
    tribe: reach
    squad: content
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/funtik
        - name: Monitoring page
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=funtik&var-container=funtik&from=now-1h&to=now
    labels:
        - reach
        - content
        - funtik
