---
apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: 'article-intelligence'
    componentType: service
spec:
    tribe: fan-experience
    squad: source
    name: article-intelligence
    slug: svc-article-intelligence
    description: ""
    ownerId: ""
    typeId: SERVICE
    dependsOn:
        - kubernetes
    fields:
        lifecycle: Active
        tier: 4
    links:
        - name: Repository
          type: REPOSITORY
          url: https://github.com/motain/article-intelligence
        - name: Prometheus Resource Metrics
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/pthfJGV4z/kubernetes-app-metrics?orgId=1&refresh=30s&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-namespace=article-intelligence&var-container=article-intelligence&from=now-1h&to=now
        - name: OnCall
          type: ON_CALL
          url: https://onefootball.app.opsgenie.com/settings/schedule/detail/191b6b6d-f7eb-4a88-977e-bcc12f38b1b9
        - name: Emissary Metrics
          type: DASHBOARD
          url: https://grafana.mgm.onefootball.com/d/z387xeWVk/ambassador-emissary-ingress?var-window=1m&orgId=1&from=now-30m&to=now&timezone=browser&var-DS_PROMETHEUS=P0F161AC36DE6FE17&var-SERVICE=article_intelligence_article_intelligence_svc_cluster_local_&refresh=5s
        - name: r-source
          type: CHAT_CHANNEL
          url: https://onefootball.slack.com/archives/C055TBZP1B9
        - name: The Source
          type: PROJECT
          url: https://onefootball.atlassian.net/jira/software/projects/SRC/boards/200
    labels:
        - article-intelligence
        - source
        - fan-experience
    customFields: null
