# OBSERVABILITY METRICS
---
apiVersion: of-catalog/v1alpha1
kind: Metric
metadata:
  name: test
  labels:
    grading-system: observability
  componentType:
    - service
    - cloud-resource
  facts:
    - id: read-otel-service-name-from-apptoml
      name: Read OTEL_SERVICE_NAME from app.toml
      type: extract
      source: github
      jsonPath: $..envs..OTEL_SERVICE_NAME
      auth: null
      repo: ${Metadata.Name}
      filePath: app.toml
    - id: "validate-otel_service_name-matches-component-name"
      name: validate OTEL_SERVICE_NAME matches component name
      type: validate
      rule: "regex_match"
      pattern: ^${Metadata.Name}$
      dependsOn: ["read-otel-service-name-from-apptoml"]
spec:
  name: test
  description: "Verifies that the component is set up to record relevant telemetry (metrics or traces)."
  format:
    unit: "Test"
---
apiVersion: of-catalog/v1alpha1
kind: Metric
metadata:
  name: test
  labels:
    grading-system: observability
  componentType:
    - service
    - cloud-resource
  facts:
    - id: fetch-slos
      name: Fetch SLOs
      type: extract
      dependsOn: []
      uri: "https://api.eu1.honeycomb.io/1/slos/${Metadata.Name}"
      source: "jsonapi"
      auth:
        header: X-Honeycomb-Team
        tokenVar: HONEYCOMB_API_KEY
      jsonPath: $..id
    - id: fetch-alerts-for-slos
      name: Fetch alerts for SLOs
      type: extract
      dependsOn:
        - fetch-slos
      uri: "https://api.eu1.honeycomb.io/1/burn_alerts/${Metadata.Name}?slo_id=:slo_id"
      source: "jsonapi"
      auth:
        header: X-Honeycomb-Team
        tokenVar: HONEYCOMB_API_KEY
      jsonPath: $.id
    - id: count-slos
      name: Count SLOs
      type: aggregate
      dependsOn:
        - fetch-slos
      method: "count"
    - id: count-alerts-for-slos
      name: Count Alerts
      type: aggregate
      dependsOn:
        - fetch-alerts-for-slos
      method: "count"
    - id: validate-alerts-for-slos
      name: Validate that counts match
      type: validate
      dependsOn:
        - count-slos
        - count-alerts-for-slos
      rule: "deps_match"
spec:
  name: test
  description: "Verifies that the component is set up to record relevant telemetry (metrics or traces)."
  format:
    unit: "Test"
---
apiVersion: of-catalog/v1alpha1
kind: Metric
metadata:
  name: test2
  labels:
    grading-system: observability
  componentType:
    - service
    - cloud-resource
  facts:
    # Validate that the OTEL_SERVICE_NAME in app.toml matches the component name
    - id: read-otel-service-name-from-apptoml
      name: Read OTEL_SERVICE_NAME from app.toml
      type: extract
      source: github
      jsonPath: $..envs..OTEL_SERVICE_NAME
      auth: null
      repo: ${Metadata.Name}
      filePath: app.toml
    - id: "validate-otel-service-name-matches-component-name"
      name: validate OTEL_SERVICE_NAME matches component name
      type: validate
      rule: "regex_match"
      pattern: ^${Metadata.Name}$
      dependsOn: ["read-otel-service-name-from-apptoml"]
    # Validate that the OTEL_RESOURCE_ATTRIBUTES in app.toml contains either of.sample_rate or of.error_sample_rate
    - id: read-otel-resource-attributes-from-apptoml
      name: Read OTEL_RESOURCE_ATTRIBUTES from app.toml
      type: extract
      source: github
      jsonPath: $..envs..OTEL_SERVICE_NAME
      auth: null
      repo: ${Metadata.Name}
      filePath: app.toml
    - id: "validate-otel-resource-attributes-sample-rate"
      name: validate OTEL_RESOURCE_ATTRIBUTES defines sample rate
      type: validate
      rule: "regex_match"
      pattern: "of\\.sample_rate=\\d+.*"
      dependsOn: ["read-otel-resource-attributes-from-apptoml"]
    - id: "validate-otel-resource-attributes-error-sample-rate"
      name: validate OTEL_RESOURCE_ATTRIBUTES defines error sample rate
      type: validate
      rule: "regex_match"
      pattern: "of\\.error_sample_rate=\\d+.*"
      dependsOn: ["read-otel-resource-attributes-from-apptoml"]
    - id: either-sample-rate-or-error-sample-rate
      name: Validate that OTEL_RESOURCE_ATTRIBUTES contains either of.sample_rate or of.error_sample_rate
      type: aggregate
      dependsOn:
        - validate-otel-resource-attributes-sample-rate
        - validate-otel-resource-attributes-error-sample-rate
      rule: "or"
spec:
  name: test2
  description: "test2"
  format:
    unit: true/false
---
apiVersion: of-catalog/v1alpha1
kind: Metric
metadata:
  name: test3
  labels:
    grading-system: observability
  componentType:
    - service
  facts:
    # Extract SLOs from Honeycomb
    - id: fetch-slos
      name: Fetch SLOs
      type: extract
      dependsOn: []
      uri: "https://api.eu1.honeycomb.io/1/slos/${Metadata.Name}"
      source: "jsonapi"
      auth:
        header: X-Honeycomb-Team
        tokenVar: HONEYCOMB_API_KEY
      jsonPath: $..id
    # Extract Alerts for each SLO from Honeycomb
    - id: fetch-alerts-for-slos
      name: Fetch alerts for SLOs
      type: extract
      dependsOn:
        - fetch-slos
      uri: "https://api.eu1.honeycomb.io/1/burn_alerts/${Metadata.Name}?slo_id=:slo_id"
      source: "jsonapi"
      auth:
        header: X-Honeycomb-Team
        tokenVar: HONEYCOMB_API_KEY
      jsonPath: $.id
    # Extract recipients for each Alert
    - id: fetch-recipients-for-alerts
      name: Fetch recipients for Alerts
      type: extract
      dependsOn:
        - fetch-slos
      uri: "https://api.eu1.honeycomb.io/1/burn_alerts/${Metadata.Name}/:alert_id"
      source: "jsonapi"
      auth:
        header: X-Honeycomb-Team
        tokenVar: HONEYCOMB_API_KEY
      jsonPath: $.recipients.target
    # # Validate that the counts of SLOs and Alerts match
    # - id: count-slos
    #   name: Count SLOs
    #   type: aggregate
    #   dependsOn:
    #     - fetch-slos
    #   method: "count"
spec:
  name: test3
  description: "3"
  format:
    unit: "3"
