apiVersion: of-catalog/v1alpha1
kind: Scorecard
metadata:
    name: cost-optimization
spec:
    id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:scorecard/4d010f50-96c4-48c0-bab5-a3dd5112b464/1b4c503f-f64d-4c05-91eb-ca49f021ce7f
    name: cost-optimization
    description: https://github.com/motain/of-catalog/blob/main/docs/grading-system/cost-optimization.md#cost-optimization-grading-system
    ownerId: 712020:edcf2690-1f3e-4310-9eb8-1ecef88d64b6
    state: PUBLISHED
    componentTypeIds:
        - SERVICE
    importance: REQUIRED
    scoringStrategyType: WEIGHT_BASED
    criteria:
        - hasMetricValue:
            id: ded22d9f-3630-4921-8ff8-2f0b20275480
            weight: 100
            name: allocation-efficiency
            metricName: allocation-efficiency
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/145c429c-b1d4-4f1f-b5c1-f322f62a34ff
            comparatorValue: 1
            comparator: EQUALS
