apiVersion: of-catalog/v1alpha1
kind: Scorecard
metadata:
    name: observability
spec:
    id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:scorecard/4d010f50-96c4-48c0-bab5-a3dd5112b464/9e5df335-1bb6-4d1c-8d62-a944d373716a
    name: observability
    description: https://github.com/motain/of-catalog/blob/main/docs/grading-system/observability.md#observability-grading-system
    ownerId: 712020:edcf2690-1f3e-4310-9eb8-1ecef88d64b6
    state: PUBLISHED
    componentTypeIds:
        - SERVICE
    importance: REQUIRED
    scoringStrategyType: WEIGHT_BASED
    criteria:
        - hasMetricValue:
            id: 24d37176-c3fc-4e6d-8143-ea37a535ee4f
            weight: 15
            name: instrumentation-check
            metricName: instrumentation-check
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/98aa724b-bd81-48f1-a002-1b443aa7906c
            comparatorValue: 1
            comparator: EQUALS
        - hasMetricValue:
            id: e06b5768-ba3e-4c6c-9289-52f463cd60c9
            weight: 15
            name: critical-alerts-slo-check
            metricName: critical-alerts-slo-check
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/65626941-1133-4262-8f52-4e126d409348
            comparatorValue: 1
            comparator: EQUALS
        - hasMetricValue:
            id: 85d281ee-bdb4-46cf-8a43-be0a6e15406d
            weight: 45
            name: alert-routing-and-notifications
            metricName: alert-routing-and-notifications
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/1f42301f-6118-4aef-8a45-80d5b63a0d93
            comparatorValue: 1
            comparator: EQUALS
        - hasMetricValue:
            id: f8a860b7-5318-4292-99cc-c527fc7a33a3
            weight: 25
            name: observability-documentation
            metricName: observability-documentation
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/8808d2fd-9ea3-4ebb-9652-bfc3ddca7c4c
            comparatorValue: 1
            comparator: EQUALS
