apiVersion: of-catalog/v1alpha1
kind: Scorecard
metadata:
    name: resiliency
spec:
    id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:scorecard/4d010f50-96c4-48c0-bab5-a3dd5112b464/d187e372-3230-48c0-94eb-e08f94a26c64
    name: resiliency
    description: https://github.com/motain/of-catalog/blob/main/docs/grading-system/resiliency.md#resiliency-grading-system
    ownerId: 712020:edcf2690-1f3e-4310-9eb8-1ecef88d64b6
    state: PUBLISHED
    componentTypeIds:
        - SERVICE
    importance: REQUIRED
    scoringStrategyType: WEIGHT_BASED
    criteria:
        - hasMetricValue:
            id: 970766c2-9980-40f3-8ece-f8cf17bfba09
            weight: 50
            name: high-availability
            metricName: high-availability
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/164a9d9b-cc07-4105-9a31-2bc46ae9c076
            comparatorValue: 1
            comparator: EQUALS
        - hasMetricValue:
            id: dd0bd193-300c-4732-87a6-95e76815e531
            weight: 50
            name: adaptive-systems
            metricName: adaptive-systems
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/d6c1a5ed-b0ce-4fed-b020-0a445cc8e6b2
            comparatorValue: 1
            comparator: EQUALS
