apiVersion: of-catalog/v1alpha1
kind: Scorecard
metadata:
    name: security
spec:
    id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:scorecard/4d010f50-96c4-48c0-bab5-a3dd5112b464/1b511a02-0163-435a-9aae-94a13d9fdd21
    name: security
    description: https://github.com/motain/of-catalog/blob/main/docs/grading-system/security.md#security-grading-system
    ownerId: 712020:edcf2690-1f3e-4310-9eb8-1ecef88d64b6
    state: PUBLISHED
    componentTypeIds:
        - SERVICE
    importance: REQUIRED
    scoringStrategyType: WEIGHT_BASED
    criteria:
        - hasMetricValue:
            id: 0fe30f03-ef06-4829-beed-8cca028cdf5a
            weight: 50
            name: security-as-pipeline
            metricName: security-as-pipeline
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/f16a5dad-816a-48db-9e96-6d1250e63659
            comparatorValue: 1
            comparator: EQUALS
        - hasMetricValue:
            id: 70a249dd-a8a0-4ecd-bd0a-604d618010a3
            weight: 50
            name: vulnerability-management
            metricName: vulnerability-management
            metricDefinitionId: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/6390dfc8-c94e-492a-8741-3fcbfa2fbddb
            comparatorValue: 1
            comparator: LESS_THAN
