// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package compute

import (
	"github.com/google/go-github/v58/github"
	"github.com/google/wire"
	"github.com/motain/fact-collector/internal/modules/metric/handler"
	"github.com/motain/fact-collector/internal/modules/metric/handler/factcollectors"
	"github.com/motain/fact-collector/internal/modules/metric/handler/factinterpreter"
	"github.com/motain/fact-collector/internal/modules/metric/repository"
	"github.com/motain/fact-collector/internal/services/compassservice"
	"github.com/motain/fact-collector/internal/services/configservice"
	"github.com/motain/fact-collector/internal/services/githubservice"
	"github.com/motain/fact-collector/internal/services/jsonservice"
	"github.com/motain/fact-collector/internal/services/keyringservice"
)

// Injectors from wire.go:

func initializeHandler() *handler.ComputeHandler {
	configService := configservice.NewConfigService()
	graphQLClientInterface := compassservice.NewGraphQLClient(configService)
	httpClientInterface := compassservice.NewHTTPClient(configService)
	compassService := compassservice.NewCompassService(configService, graphQLClientInterface, httpClientInterface)
	repositoryRepository := repository.NewRepository(compassService)
	keyringService := keyringservice.NewKeyringService()
	repositoriesService := githubservice.NewGitHubRepositoriesClient(configService, keyringService)
	gitHubRepositoriesService := githubservice.NewGitHubRepositoriesService(repositoriesService)
	githubFactCollector := factcollectors.NewGithubFactCollector(gitHubRepositoriesService)
	jsonServiceInterface := jsonservice.NewJSONService(configService)
	jsonapiFactCollector := factcollectors.NewJSONAPIFactCollector(jsonServiceInterface)
	factInterpreter := factinterpreter.NewFactInterpreter(githubFactCollector, jsonapiFactCollector)
	computeHandler := handler.NewComputeHandler(repositoryRepository, factInterpreter)
	return computeHandler
}

// wire.go:

var ProviderSet = wire.NewSet(keyringservice.NewKeyringService, wire.Bind(new(keyringservice.KeyringServiceInterface), new(*keyringservice.KeyringService)), configservice.NewConfigService, wire.Bind(new(configservice.ConfigServiceInterface), new(*configservice.ConfigService)), compassservice.NewGraphQLClient, compassservice.NewHTTPClient, compassservice.NewCompassService, wire.Bind(new(compassservice.CompassServiceInterface), new(*compassservice.CompassService)), githubservice.NewGitHubRepositoriesClient, wire.Bind(new(githubservice.GitHubRepositoriesInterface), new(*github.RepositoriesService)), githubservice.NewGitHubRepositoriesService, wire.Bind(new(githubservice.GitHubRepositoriesServiceInterface), new(*githubservice.GitHubRepositoriesService)), jsonservice.NewJSONService, repository.NewRepository, wire.Bind(new(repository.RepositoryInterface), new(*repository.Repository)), factcollectors.NewGithubFactCollector, wire.Bind(new(factcollectors.GithubFactCollectorInterface), new(*factcollectors.GithubFactCollector)), factcollectors.NewJSONAPIFactCollector, wire.Bind(new(factcollectors.JSONAPIFactCollectorInterface), new(*factcollectors.JSONAPIFactCollector)), factinterpreter.NewFactInterpreter, wire.Bind(new(factinterpreter.FactInterpreterInterface), new(*factinterpreter.FactInterpreter)), handler.NewComputeHandler)
