---
apiVersion: of-catalog/v1alpha1
kind: Metric
metadata:
  name: allocation-efficiency
  labels:
    grading-system: cost-optimization
  componentType:
    - service
    - cloud-resource
  facts:
    - id: check-app-toml-resource-request
      name: Check if CPU requests and memory requests are defined in app.toml under [service] or [service.production]
      source: github
      repo: "${Metadata.Name}"
      type: extract
      filePath: "app.toml"
      jsonPath: (.service.cpu_requests // .service.production.cpu_requests | . != null) and (.service.memory_requests // .service.production.memory_requests | . != null)
    - id: check-app-toml-cpu-limits
      name: Check if CPU requests and memory requests are defined in app.toml under [service] or [service.production]
      source: github
      repo: "${Metadata.Name}"
      type: extract
      filePath: "app.toml"
      jsonPath: .service.cpu_limits // .service.production.cpu_limits | not
    - id: check-app-toml-cpu-limits
      name: Check if CPU requests and memory requests are defined in app.toml under [service] or [service.production]
      source: github
      repo: "${Metadata.Name}"
      type: extract
      filePath: "app.toml"
      jsonPath: .service.memory_limits // .service.production.memory_limits | .==null
    - id: aggregate-resource-requests
      name: check resource requests and limits
      type: aggregate
      dependsOn:
        - check-app-toml-resource-request
        - check-app-toml-cpu-limits
        - check-app-toml-memory-limits
      method: "and"
spec:
  name: allocation-efficiency
  description: "Verifies if the component has defined resource allocations in an efficient way"
  format:
    unit: "Allocation Efficiency"
