// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/motain/of-catalog/internal/services/factsystem/factcollectors (interfaces: JSONAPIFactCollectorInterface)

// Package factcollectors is a generated GoMock package.
package factcollectors

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dtos "github.com/motain/of-catalog/internal/services/factsystem/dtos"
)

// MockJSONAPIFactCollectorInterface is a mock of JSONAPIFactCollectorInterface interface.
type MockJSONAPIFactCollectorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockJSONAPIFactCollectorInterfaceMockRecorder
}

// MockJSONAPIFactCollectorInterfaceMockRecorder is the mock recorder for MockJSONAPIFactCollectorInterface.
type MockJSONAPIFactCollectorInterfaceMockRecorder struct {
	mock *MockJSONAPIFactCollectorInterface
}

// NewMockJSONAPIFactCollectorInterface creates a new mock instance.
func NewMockJSONAPIFactCollectorInterface(ctrl *gomock.Controller) *MockJSONAPIFactCollectorInterface {
	mock := &MockJSONAPIFactCollectorInterface{ctrl: ctrl}
	mock.recorder = &MockJSONAPIFactCollectorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJSONAPIFactCollectorInterface) EXPECT() *MockJSONAPIFactCollectorInterfaceMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockJSONAPIFactCollectorInterface) Check(arg0 dtos.Fact) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockJSONAPIFactCollectorInterfaceMockRecorder) Check(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockJSONAPIFactCollectorInterface)(nil).Check), arg0)
}

// Inspect mocks base method.
func (m *MockJSONAPIFactCollectorInterface) Inspect(arg0 dtos.Fact) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inspect", arg0)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Inspect indicates an expected call of Inspect.
func (mr *MockJSONAPIFactCollectorInterfaceMockRecorder) Inspect(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inspect", reflect.TypeOf((*MockJSONAPIFactCollectorInterface)(nil).Inspect), arg0)
}
