// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/motain/of-catalog/internal/services/factsystem/factcollectors (interfaces: GithubFactCollectorInterface)

// Package factcollectors is a generated GoMock package.
package factcollectors

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dtos "github.com/motain/of-catalog/internal/services/factsystem/dtos"
)

// MockGithubFactCollectorInterface is a mock of GithubFactCollectorInterface interface.
type MockGithubFactCollectorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGithubFactCollectorInterfaceMockRecorder
}

// MockGithubFactCollectorInterfaceMockRecorder is the mock recorder for MockGithubFactCollectorInterface.
type MockGithubFactCollectorInterfaceMockRecorder struct {
	mock *MockGithubFactCollectorInterface
}

// NewMockGithubFactCollectorInterface creates a new mock instance.
func NewMockGithubFactCollectorInterface(ctrl *gomock.Controller) *MockGithubFactCollectorInterface {
	mock := &MockGithubFactCollectorInterface{ctrl: ctrl}
	mock.recorder = &MockGithubFactCollectorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGithubFactCollectorInterface) EXPECT() *MockGithubFactCollectorInterfaceMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockGithubFactCollectorInterface) Check(arg0 dtos.Fact) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockGithubFactCollectorInterfaceMockRecorder) Check(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockGithubFactCollectorInterface)(nil).Check), arg0)
}

// Inspect mocks base method.
func (m *MockGithubFactCollectorInterface) Inspect(arg0 dtos.Fact) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inspect", arg0)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Inspect indicates an expected call of Inspect.
func (mr *MockGithubFactCollectorInterfaceMockRecorder) Inspect(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inspect", reflect.TypeOf((*MockGithubFactCollectorInterface)(nil).Inspect), arg0)
}
