apiVersion: of-catalog/v1alpha1
kind: Component
metadata:
    name: peregrine
    componentType: service
spec:
    id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:component/4d010f50-96c4-48c0-bab5-a3dd5112b464/771c4a71-419c-427a-9db6-87a02fbf1b19
    name: peregrine
    slug: svc-peregrine
    description: Not Provided
    configVersion: 0
    typeId: SERVICE
    ownerId: ari:cloud:identity::team/f4797497-61c0-4312-93f3-8d0f31ace225
    dependsOn:
        - kubernetes
        - kubernetes
    fields:
        lifecycle: Active
        tier: 4
    links: []
    documents: []
    labels:
        - developer-xp
        - platform
    metricSources: {}
    tribe: platform
    squad: developer-xp
