# PRODUCTION-READINESS
---
apiVersion: of-catalog/v1alpha1
kind: Metric
metadata:
    name: metric-test-1
    labels:
        grading-system: production-readiness
    componentType:
        - service
        - cloud-resource
    facts:
        all: # Boolean
          - source: "github"
            uri: ""
            name: app-toml-exists
            repo: "${Spec.Name}"
            branch: ""
            factType: fileExists
            filePath: app.toml
            regexPattern: ""
            jsonPath: ""
            repoProperty: ""
            expectedValue: ""
          - source: "github"
            uri: ""
            name: app-toml-envs-otel-service-name
            repo: "${Spec.Name}"
            branch: ""
            factType: fileJsonPath
            filePath: app.toml
            regexPattern: ""
            jsonPath: envs.OTEL_SERVICE_NAME
            repoProperty: ""
            expectedValue: "${Spec.Name}"
          - source: "github"
            uri: ""
            name: exposes-health-endpoint
            repo: "${Spec.Name}"
            branch: ""
            factType: repoSearch
            filePath: ""
            reposSearchQuery: "@app.get('/health')&type=code"
            regexPattern: ""
            jsonPath: ""
            repoProperty: ""
            expectedValue: ""
spec:
    name: metric-test-1
    description: example metric-1 used to test cli
    format:
        unit: msg/sec
---
apiVersion: of-catalog/v1alpha1
kind: Metric
metadata:
    name: metric-test-2
    labels:
        grading-system: production-readiness
    componentType:
        - service
        - cloud-resource
    facts:
        inspect: # Boolean
          source: "jsonapi"
          uri: "https://pokeapi.co/api/v2/pokemon/ditto"
          name: pokemon-base-experience
          repo: ""
          branch: ""
          factType: fileJsonPath
          filePath: ""
          regexPattern: ""
          jsonPath: base_experience
          repoProperty: ""
          expectedValue: ""
          auth:
            header: Authorization
            tokenEnvVariable: HONEYCOMB_API_KEY
spec:
    name: metric-test-2
    description: example metric-1 used to test cli
    format:
        unit: msg/sec
---
apiVersion: of-catalog/v1alpha1
kind: Metric
metadata:
    name: metric-test-3
    labels:
        grading-system: production-readiness
    componentType:
        - service
        - cloud-resource
    facts:
        all: # Boolean
          - source: "jsonapi"
            uri: "https://pokeapi.co/api/v2/pokemon/ditto"
            name: pokemon-height
            repo: ""
            branch: ""
            factType: fileJsonPath
            filePath: ""
            regexPattern: ""
            jsonPath: height
            repoProperty: ""
            expectedValue: "3"
        any:
          - source: "jsonapi"
            uri: "https://pokeapi.co/api/v2/pokemon/ditto"
            name: pokemon-weight
            repo: ""
            branch: ""
            factType: fileJsonPath
            filePath: ""
            regexPattern: ""
            jsonPath: weight
            repoProperty: ""
            expectedValue: ""
            expectedexpectedFormula: "> 50"
            auth:
                header: "Authorization"
                tokenEnvVariable: "HONEYCOMB_API_KEY"
spec:
    name: metric-test-3
    description: example metric-3 used to test cli
    format:
        unit: strong enough
