# PRODUCTION-READINESS
---
apiVersion: of-catalog/v1alpha1
kind: Metric
metadata:
    name: metric-test-1
    labels:
        grading-system: production-readiness
    componentType:
        - service
        - cloud-resource
    facts:
        all: # Boolean
          - source: "github"
            uri: ""
            name: app-toml-exists
            repo: simple-service
            branch: ""
            factType: fileExists
            filePath: app.toml
            regexPattern: ""
            jsonPath: ""
            repoProperty: ""
            expectedValue: ""
          - source: "github"
            uri: ""
            name: app-toml-envs-otel-service-name
            repo: simple-service
            branch: ""
            factType: fileJsonPath
            filePath: app.toml
            regexPattern: ""
            jsonPath: envs.OTEL_SERVICE_NAME
            repoProperty: ""
            expectedValue: simple-service
spec:
    name: metric-test-1
    description: example metric-1 used to test cli
    format:
        unit: msg/sec
---
apiVersion: of-catalog/v1alpha1
kind: Metric
metadata:
    name: metric-test-2
    labels:
        grading-system: production-readiness
    componentType:
        - service
        - cloud-resource
    facts:
        all: # Boolean
          - source: "github"
            uri: ""
            name: app-toml-exists
            repo: simple-service
            branch: ""
            factType: fileExists
            filePath: app.toml
            regexPattern: ""
            jsonPath: ""
            repoProperty: ""
            expectedValue: ""
          - source: "github"
            uri: ""
            name: app-toml-envs-otel-service-name
            repo: simple-service
            branch: ""
            factType: fileJsonPath
            filePath: app.toml
            regexPattern: ""
            jsonPath: envs.OTEL_SERVICE_NAME
            repoProperty: ""
            expectedValue: simple-service
spec:
    name: metric-test-2
    description: example metric-1 used to test cli
    format:
        unit: msg/sec



