// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package compute

import (
	"github.com/google/wire"
	"github.com/motain/fact-collector/internal/modules/component/handler"
	"github.com/motain/fact-collector/internal/modules/component/repository"
	"github.com/motain/fact-collector/internal/services/compassservice"
	"github.com/motain/fact-collector/internal/services/configservice"
	"github.com/motain/fact-collector/internal/services/factsystem/factcollectors"
	"github.com/motain/fact-collector/internal/services/factsystem/factinterpreter"
	"github.com/motain/fact-collector/internal/services/githubservice"
	"github.com/motain/fact-collector/internal/services/jsonservice"
	"github.com/motain/fact-collector/internal/services/keyringservice"
)

// Injectors from wire.go:

func initializeHandler() *handler.ComputeHandler {
	configService := configservice.NewConfigService()
	graphQLClientInterface := compassservice.NewGraphQLClient(configService)
	httpClientInterface := compassservice.NewHTTPClient(configService)
	compassService := compassservice.NewCompassService(configService, graphQLClientInterface, httpClientInterface)
	repositoryRepository := repository.NewRepository(compassService)
	keyringService := keyringservice.NewKeyringService()
	gitHubClientInterface := githubservice.NewGitHubClient(configService, keyringService)
	gitHubService := githubservice.NewGitHubService(gitHubClientInterface)
	githubFactCollector := factcollectors.NewGithubFactCollector(gitHubService)
	jsonServiceInterface := jsonservice.NewJSONService(configService)
	jsonapiFactCollector := factcollectors.NewJSONAPIFactCollector(configService, jsonServiceInterface)
	componentFactCollector := factcollectors.NewComponentFactCollector()
	factInterpreter := factinterpreter.NewFactInterpreter(githubFactCollector, jsonapiFactCollector, componentFactCollector)
	computeHandler := handler.NewComputeHandler(repositoryRepository, factInterpreter)
	return computeHandler
}

// wire.go:

var ProviderSet = wire.NewSet(keyringservice.NewKeyringService, wire.Bind(new(keyringservice.KeyringServiceInterface), new(*keyringservice.KeyringService)), configservice.NewConfigService, wire.Bind(new(configservice.ConfigServiceInterface), new(*configservice.ConfigService)), compassservice.NewGraphQLClient, compassservice.NewHTTPClient, compassservice.NewCompassService, wire.Bind(new(compassservice.CompassServiceInterface), new(*compassservice.CompassService)), githubservice.NewGitHubClient, githubservice.NewGitHubService, wire.Bind(new(githubservice.GitHubServiceInterface), new(*githubservice.GitHubService)), jsonservice.NewJSONService, repository.NewRepository, wire.Bind(new(repository.RepositoryInterface), new(*repository.Repository)), factcollectors.NewGithubFactCollector, wire.Bind(new(factcollectors.GithubFactCollectorInterface), new(*factcollectors.GithubFactCollector)), factcollectors.NewJSONAPIFactCollector, wire.Bind(new(factcollectors.JSONAPIFactCollectorInterface), new(*factcollectors.JSONAPIFactCollector)), factcollectors.NewComponentFactCollector, wire.Bind(new(factcollectors.ComponentFactCollectorInterface), new(*factcollectors.ComponentFactCollector)), factinterpreter.NewFactInterpreter, wire.Bind(new(factinterpreter.FactInterpreterInterface), new(*factinterpreter.FactInterpreter)), handler.NewComputeHandler)
