apiVersion: of-catalog/v1alpha1
kind: Metric
metadata:
    name: alert-routing-and-notifications
    labels:
        grading-system: observability
    componentType:
        - service
    facts:
        - id: fetch-slos
          name: Fetch SLOs
          type: extract
          source: jsonapi
          uri: https://api.eu1.honeycomb.io/1/slos/${Metadata.Name}
          jsonPath: .[].id
          auth:
            header: X-Honeycomb-Team
            tokenVar: HONEYCOMB_API_KEY
          rule: jsonpath
        - id: fetch-alerts-for-slos
          name: Fetch alerts for SLOs
          type: extract
          dependsOn:
            - fetch-slos
          source: jsonapi
          uri: https://api.eu1.honeycomb.io/1/burn_alerts/${Metadata.Name}?slo_id=:slo_id
          jsonPath: .[].id
          auth:
            header: X-Honeycomb-Team
            tokenVar: HONEYCOMB_API_KEY
          rule: jsonpath
        - id: fetch-recipients-for-alerts
          name: Fetch recipients for Alerts
          type: extract
          dependsOn:
            - fetch-alerts-for-slos
          source: jsonapi
          uri: https://api.eu1.honeycomb.io/1/burn_alerts/${Metadata.Name}/:alert_id
          jsonPath: .recipients[].target
          auth:
            header: X-Honeycomb-Team
            tokenVar: HONEYCOMB_API_KEY
          rule: jsonpath
        - id: validate-each-target-is-not-empty-string
          name: Validate that each target is not an empty string
          type: validate
          dependsOn:
            - fetch-recipients-for-alerts
          rule: regex_match
          pattern: ^\S.*$
        - id: validate-all-targets-are-not-empty-strings
          name: Validate that all targets are not empty strings
          type: aggregate
          dependsOn:
            - validate-each-target-is-not-empty-string
          method: and
spec:
    id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/1f42301f-6118-4aef-8a45-80d5b63a0d93
    name: alert-routing-and-notifications
    description: https://github.com/motain/of-catalog/blob/main/docs/grading-system/observability.md#alert-routing-and-notifications
    format:
        unit: Critical Alerts/SLO Check
