---
apiVersion: of-catalog/v1alpha1
kind: Metric
metadata:
  name: allocation-efficiency
  labels:
    grading-system: cost-optimization
  componentType:
    - service
    - cloud-resource
  facts:
    - id: check-app-toml-resource-request
      name: Check if CPU requests and memory requests are defined in app.toml under [service] or [service.production]
      type: extract
      source: github
      jsonPath: (.service.cpu_requests // .service.production.cpu_requests | . != null) and (.service.memory_requests // .service.production.memory_requests | . != null)
      repo: ${Metadata.Name}
      filePath: app.toml
      rule: jsonpath
    - id: check-app-toml-cpu-limits
      name: Check if CPU limits are not defined in app.toml under [service] or [service.production]
      type: extract
      source: github
      jsonPath: .service.cpu_limits // .service.production.cpu_limits | not
      repo: ${Metadata.Name}
      filePath: app.toml
      rule: jsonpath
    - id: check-app-toml-memory-limits
      name: Check if  memory limits are defined in app.toml under [service] or [service.production]
      type: extract
      source: github
      jsonPath: .service.memory_limits // .service.production.memory_limits | . != null
      repo: ${Metadata.Name}
      filePath: app.toml
      rule: jsonpath
    - id: aggregate-resource-requests
      name: check resource requests and limits
      type: aggregate
      dependsOn:
        - check-app-toml-resource-request
        - check-app-toml-cpu-limits
        - check-app-toml-memory-limits
      method: and
spec:
  id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/0280d248-c53a-4dcf-a5a4-945cdd931406
  name: allocation-efficiency
  description: https://github.com/motain/of-catalog/blob/main/docs/grading-system/cost-optimization.md#cost-optimization-grading-system
  format:
    unit: Allocation Efficiency