apiVersion: of-catalog/v1alpha1
kind: Metric
metadata:
    name: deployment-readiness
    labels:
        grading-system: production-readiness
    componentType:
        - service
        - cloud-resource
    facts:
        - id: deployment-readiness-replicas-service-production
          name: Check deployment readiness where min != Max, Min >= 3 and Max > 3
          type: extract
          source: github
          jsonPath: (.service.production.replicas_min != .service.production.replicas_max) and (.service.production.replicas_min >= 3) and (.service.production.replicas_max > 3)
          repo: ${Metadata.Name}
          filePath: app.toml
          rule: jsonpath
        - id: deployment-readiness-replicas-service
          name: Check deployment readiness where min != Max, Min >= 3 and Max > 3
          type: extract
          source: github
          jsonPath: (.service.replicas_min != .service.replicas_max) and (.service.replicas_min >= 3) and (.service.replicas_max > 3)
          repo: ${Metadata.Name}
          filePath: app.toml
          rule: jsonpath
        - id: aggregate-replicas
          name: Check deployment readiness where min != Max, Min >= 3 and Max > 3
          type: aggregate
          dependsOn:
            - deployment-readiness-replicas-service-production
            - deployment-readiness-replicas-service
          method: or
spec:
    id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/05fd721b-1464-4973-bee6-ac873c3b75c1
    name: deployment-readiness
    description: https://github.com/motain/of-catalog/blob/main/docs/grading-system/production-readiness.md#deployment-readiness
    format:
        unit: Deployment Standards
