apiVersion: of-catalog/v1alpha1
kind: Metric
metadata:
    name: high-availability
    labels:
        grading-system: resiliency
    componentType:
        - service
        - cloud-resource
    facts:
        - id: app-toml-hpa-target-cpu
          type: extract
          source: github
          jsonPath: .service.target_cpu_utilization_percentage // .service.production.target_cpu_utilization_percentage | . >= 20
          repo: ${Metadata.Name}
          filePath: app.toml
          rule: jsonpath
        - id: app-toml-hpa-target-memory
          type: extract
          source: github
          jsonPath: .service.target_memory_utilization_percentage // .service.production.target_memory_utilization_percentage | . >= 20
          repo: ${Metadata.Name}
          filePath: app.toml
          rule: jsonpath
        - id: cpu-and-memory-hpa-are-set
          name: Validate that CPU and Memory Horizontal Pod Autoscalers are set
          type: aggregate
          dependsOn:
            - app-toml-hpa-target-cpu
            - app-toml-hpa-target-memory
          method: or
spec:
    id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/43e2c6ef-1a41-4fd6-b0e9-d7d7545681fd
    name: high-availability
    description: https://github.com/motain/of-catalog/blob/main/docs/grading-system/resiliency.md#high-availability
    format:
        unit: High Availability
