apiVersion: of-catalog/v1alpha1
kind: Metric
metadata:
    name: observability-documentation
    labels:
        grading-system: observability
    componentType:
        - service
        - cloud-resource
    facts:
        - id: extract-observability-md
          name: Extract observability.md
          type: extract
          source: github
          repo: ${Metadata.Name}
          filePath: docs/observability.md
          rule: notempty
spec:
    id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/8808d2fd-9ea3-4ebb-9652-bfc3ddca7c4c
    name: observability-documentation
    description: https://github.com/motain/of-catalog/blob/main/docs/grading-system/observability.md#observability-documentation
    format:
        unit: Observability Documentation
