apiVersion: of-catalog/v1alpha1
kind: Metric
metadata:
    name: vulnerability-management
    labels:
        grading-system: security
    componentType:
        - service
        - cloud-resource
    facts:
        - id: service-vulnerabilities-prometheus
          name: Get summary of vulnerabilities for services from Prometheus reports
          type: extract
          source: prometheus
          prometheusQuery: sum(trivy_image_vulnerabilities{namespace="${Metadata.Name}", severity="Critical" })
spec:
    id: ari:cloud:compass:fca6a80f-888b-4079-82e6-3c2f61c788e2:metric-definition/4d010f50-96c4-48c0-bab5-a3dd5112b464/6390dfc8-c94e-492a-8741-3fcbfa2fbddb
    name: vulnerability-management
    description: https://github.com/motain/of-catalog/blob/main/docs/grading-system/security.md#vulnerability-management
    format:
        unit: Vulnerability Management
