---
name: Compute Component Metrics

on:
  workflow_dispatch:
    inputs:
      component:
        description: 'Name of the components to compute metrics for. Comma-separated list or empty for all components.'
        required: false
        default: ''
        type: string
  schedule:
    - cron: '0 */3 * * *'

concurrency:
  group: compute-components-${{ github.head_ref }}${{ inputs.component }}
  cancel-in-progress: true

permissions: write-all

jobs:

  compute:
    runs-on: [ self-hosted, linux, x64, core-team-only ]
    timeout-minutes: 60
    env:
      HONEYCOMB_API_KEY: ${{ secrets.HONEYCOMB_API_KEY}}
      COMPASS_API_TOKEN: ${{ secrets.COMPASS_TOKEN}}
      COMPASS_API_BASE_URL: https://onefootball.atlassian.net/gateway/api/graphql
      COMPASS_CLOUD_ID: fca6a80f-888b-4079-82e6-3c2f61c788e2
      PROMETHEUS_WORKSPACE_URL: https://aps-workspaces.eu-west-1.amazonaws.com/workspaces/ws-841dbf21-00d1-4a0a-96a9-25de0ecb9562
      AWS_REGION: eu-west-1

    steps:
      - uses: actions/checkout@v4

      - uses: motain/onefootball-actions/aws-login@master
        with:
          environment: production
          role: gha-oidc-admin

      - name: Install compass-compute version
        if: hashFiles('~/.local/bin/compass-compute') == ''
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_DEPENDENCIES_GITHUB_TOKEN }}
        run: |
          gh release download -R motain/compass-compute -p " compass-compute-v*-linux-amd64.tar.gz" \
           && tar -xvf compass-compute-v*-linux-amd64.tar.gz  --skip-existing \
           && mv compass-compute-linux-amd64 compass-compute \
           && chmod +x compass-compute \
           && mkdir -p $HOME/.local/bin \
           && cp compass-compute $HOME/.local/bin/ \
           && echo "$HOME/.local/bin" >> $GITHUB_PATH

      - run: compass-compute compute -A
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.PAAS_CREATE_AND_MERGE_TO_HELM_CHARTS }}

      - run: compass-compute compute ${{ github.event.inputs.component }}
        if: ${{ github.event.inputs.component != '' }}
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.PAAS_CREATE_AND_MERGE_TO_HELM_CHARTS }}
