name: ComputeComponentMetrics

on:
  push:
    branches:
      - main
    paths:
      - 'config/components/**'

  workflow_dispatch:
    inputs:
      component:
        description: 'Name of the component to monitor as specified in the app.toml file'
        required: true
        type: string

concurrency:
  group: production-${{ github.head_ref }}
  cancel-in-progress: true

permissions: write-all

jobs:
  generate-matrix:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    name: Generate job matrices
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Generate matrix
        id: generate-matrix
        uses: motain/onefootball-actions/changed-matrix@master
        with:
          pattern: production/(?P<project>[^/]+)

  monitor-service-from-matrix:
    needs: generate-matrix
    strategy:
      fail-fast: false
    if: ${{ fromJson(toJSON(needs.generate-matrix.outputs.matrix)) }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PRIVATE_GH_TOKEN_RELEASE_WITH_ASSETS}}
      COMPASS_TOKEN: ${{ secrets.COMPASS_TOKEN}}
      GITHUB_ORG: motain
      COMPASS_HOST: onefootball.atlassian.net
      HONEYCOMB_API_KEY: ${{ secrets.HONEYCOMB_API_KEY}}
    steps:
    - uses: actions/checkout@v4

    - run: |
        curl -J -L \
          -H "Accept: application/octet-stream" \
          -H "Authorization: token ${{ secrets.PRIVATE_GH_TOKEN_RELEASE_WITH_ASSETS}}" \
          -o ofc \
          $(curl -s -H "Authorization: token ${{ secrets.PRIVATE_GH_TOKEN_RELEASE_WITH_ASSETS}}" "https://api.github.com/repos/motain/of-catalog/releases/latest" | jq -r '.assets[0].url')
          chmod +x ofc

    - run: |
        ./ofc component compute -a -c ${{ matrix.project }}

  monitor-service-from-manual-trigger:
    strategy:
      fail-fast: false
    if: ${{ github.event.inputs.component }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PRIVATE_GH_TOKEN_RELEASE_WITH_ASSETS}}
      COMPASS_TOKEN: ${{ secrets.COMPASS_TOKEN}}
      GITHUB_ORG: motain
      COMPASS_HOST: onefootball.atlassian.net
      HONEYCOMB_API_KEY: ${{ secrets.HONEYCOMB_API_KEY}}
    steps:
    - uses: actions/checkout@v4

    - run: |
        curl -J -L \
          -H "Accept: application/octet-stream" \
          -H "Authorization: token ${{ secrets.PRIVATE_GH_TOKEN_RELEASE_WITH_ASSETS}}" \
          -o ofc \
          $(curl -s -H "Authorization: token ${{ secrets.PRIVATE_GH_TOKEN_RELEASE_WITH_ASSETS}}" "https://api.github.com/repos/motain/of-catalog/releases/latest" | jq -r '.assets[0].url')
          chmod +x ofc

    - run: |
        ./ofc component compute -a -c ${{ github.event.inputs.component }}
