name: SyncComponents

on:
  push:
    branches:
      - main
    paths:
      - 'config/components/**'
  workflow_dispatch:

concurrency:
  group: components
  cancel-in-progress: true

permissions: write-all

jobs:
  sync-components:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PRIVATE_GH_TOKEN_RELEASE_WITH_ASSETS}}
      COMPASS_TOKEN: ${{ secrets.COMPASS_TOKEN}}
      GITHUB_ORG: motain
      COMPASS_HOST: onefootball.atlassian.net
      HONEYCOMB_API_KEY: ${{ secrets.HONEYCOMB_API_KEY}}
    steps:
    - uses: actions/checkout@v4
    - run: |
        curl -J -L \
          -H "Accept: application/octet-stream" \
          -H "Authorization: token ${{ secrets.PRIVATE_GH_TOKEN_RELEASE_WITH_ASSETS}}" \
          -o ofc \
          $(curl -s -H "Authorization: token ${{ secrets.PRIVATE_GH_TOKEN_RELEASE_WITH_ASSETS}}" "https://api.github.com/repos/motain/of-catalog/releases/latest" | jq -r '.assets[0].url')
          chmod +x ofc
    - run: |
        ./ofc component apply -l ./config/components

    - name: Commit and push state changes
      run: |
        git config user.email 'devops@onefootball.com'
        git config user.name 'Onefootball Helm Charts'

        git checkout -b "paas/sync-components-${{ github.sha }}"
        git add .state
        git commit -m "chore(components): update state"
        git push origin paas/sync-components-${{ github.sha }}

        gh pr create --title "chore(components): update state" --body "PaaS: update components state automation." --base main
        gh pr merge --squash --delete-branch
