name: SyncComponents

on:
  push:
    branches:
    - main
    paths:
    - 'config/components/**'
  workflow_dispatch:

concurrency:
  group: compute-components-${{ github.head_ref }}
  cancel-in-progress: false # We need to terminate the sync of the component

permissions: write-all

jobs:

  generate-matrix:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    name: Generate job matrices
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Generate matrix
        id: generate-matrix
        uses: motain/onefootball-actions/changed-matrix@master
        with:
          pattern: config/components/component-(?P<project>[^/]+)\.yaml

  sync-components:
    needs: generate-matrix
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PRIVATE_GH_TOKEN_RELEASE_WITH_ASSETS}}
      COMPASS_TOKEN: ${{ secrets.COMPASS_TOKEN}}
      COMPASS_CLOUD_ID: fca6a80f-888b-4079-82e6-3c2f61c788e2
      GITHUB_ORG: motain
      COMPASS_HOST: onefootball.atlassian.net
      HONEYCOMB_API_KEY: ${{ secrets.HONEYCOMB_API_KEY}}
    steps:
    - uses: actions/checkout@v4
    - run: |
        curl -J -L \
          -H "Accept: application/octet-stream" \
          -H "Authorization: token ${{ secrets.PRIVATE_GH_TOKEN_RELEASE_WITH_ASSETS}}" \
          -o ofc \
          $(curl -s -H "Authorization: token ${{ secrets.PRIVATE_GH_TOKEN_RELEASE_WITH_ASSETS}}" "https://api.github.com/repos/motain/of-catalog/releases/latest" | jq -r '.assets[0].url')
          chmod +x ofc
    - run: |
        ./ofc component apply -l ./config/components -c ${{ matrix.project }}

    - name: Commit and push state changes
      run: |
        BRANCH="paas/sync-components-${{ github.sha }}"

        git config user.email 'devops@onefootball.com'
        git config user.name 'PaaS user'

        git checkout -b "$BRANCH"
        git add .state

        git commit -m "chore(components): [PaaS] update state for ${{ matrix.project }}"
        git push -f origin "$BRANCH"

        gh pr create --title "chore(components): update state" --body "PaaS: update components state automation." --base main
        gh pr merge --squash --delete-branch

    - name: Trigger compute-component-metrics workflow
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh workflow run compute-component-metrics.yaml -f component=${{ matrix.project }}
